#push code to elect port on server 1
#open it 1
#python check 
#choose what environment we need 
#push to prod on server to port  80
#
name: Stage 
on:
  workflow_dispatch:
    inputs:
      releaseType:
        desription: 'Where to release (staging or prod)?'
        required: true
        default: 'staging'
  
jobs: 
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest version 
        uses: appleboy/scp-action@master
        with:
          local: sitefile
          remote: /root/test
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart nginx
      - name: Check webpage 
        run : python .github/workflows/check-usebility.py

  prod:
    runs-on: ubuntu-latest
    needs: [stage]
    steps:
      - name: Checkout latest version 
        uses: appleboy/scp-action@master
        with:
          local: sitefile
          remote: /root/prod
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo systemctl restart nginx
      - name: Check webpage 
        run : python .github/workflows/.devops/check-usebility.py
