#push code to elect port on server 1
#open it 1
#python check 
#choose what environment we need 
#push to prod on server to port  80
#
name: Stage 
on:
  workflow_dispatch:
    inputs:
      releaseType:
        desription: 'Where to release (staging or prod)?'
        required: true
        default: 'staging'
  
jobs: 
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      - uses: actions/checkout@v2
      - name: Copy file via ssh password
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "sitefile"
        target: "/test"
        script: |
          sudo systemctl restart nginx
      - name: Check webpaae 
        run : python .github/workflows/check-usebility.py

  prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
      - uses: actions/checkout@v2
      - name: Copy file via ssh password
      uses: ./
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "sitefile"
        target: "/prod"
        script: |
          sudo systemctl restart nginx
      - name: Check webpaae 
        run : python .github/workflows/check-usebility.py
