#push code to elect port on server 1
#open it 1
#python check 
#choose what environment we need 
#push to prod on server to port  80
#
name: Deploy
on:
  workflow_dispatch:
    inputs:
      releaseType:
        desription: 'Where to release (staging or prod)?'
        required: true
        default: 'staging'
  
jobs: 
  staging:
    name: Build staging on server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PASSWORD }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "sitefile/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: /test
          EXCLUDE: "sitefile/"
      - name: Check webpage 
        run : python .github/workflows/check-usebility.py

  prod:
    name: Build prod on server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1
      - name: Deploy to PROD Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PASSWORD }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "sitefile/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER}}
          TARGET: /prod
          EXCLUDE: "sitefile/"
      - name: Check webpage 
        run : python .github/workflows/check-usebility.py
